### ISSUE TITLE
Error on docker-compose up -d

### ISSUE THREAD

**Issue by keale** [SciCatProject/scicatlive#17]
Dear developers, 
We consider to use SciCat at GSI/HI-Jena. I try to get a SciCat test instance in an Ubuntu_20.04 VirtualBox VM running at a Win10 Pro host. I installed Docker acording to instruction from [docker.com](https://docs.docker.com/engine/install/ubuntu/) , install using repository. After this it was neccessery to install docker-compose additionaly.

`sudo apt install docker-compose`

Now I am able to run the command, but i get error like:
`ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for volumes: 'mongodb_data'
Unsupported config option for services: 'mongodb_seed`

I'm not realy familiar with docker, but assume that a container is supposed to be self-sufficient. Do I need to install mongo_db separately in the VM?

Best wishes, 
Alexander Kessler

**Comment by minottic** [comment]
closed by: #18
