### ISSUE TITLE
Swagger UI forwarding in Traefik not working

### ISSUE THREAD

**Issue by consolethinks** [SciCatProject/scicatlive#20]
In the docker-compose.yaml, in services->backend->labels, the line ``- "traefik.http.routers.backend.rule=PathPrefix(`/api`, `/auth`, `/explorer-next`)"`` must be changed to ``- "traefik.http.routers.backend.rule=PathPrefix(`/api`, `/auth`, `/explorer`)"`` in order to properly forward the endpoint for the Swagger UI (even on the up-to-date new backend). Otherwise, `localhost/explorer-next` will only give a 404 error.

**Comment by minottic** [comment]
closed by: #23
