### ISSUE TITLE
Mock archiving system in a container

### ISSUE THREAD

**Issue by sbliven** [SciCatProject/scicatlive#22]
A complete SciCat installation should include an archiving system. This is currently treated as external to scicat by much of the documentation so it can be difficult to know how to implement it. It is also necessary for integration tests involving data transfer upon archiving and retrieval.

I suggest a minimal example container in scicatlive with the following features:

- data volumes representing 'unarchived' and 'archived' data
- protocol for copying data to and from the 'unarchived' volume (eg S3, sftp, etc)
- Basic HTTP server implementing the job API
  - Listens for job create events (probably via URL action)
  - Moves files to the 'archived' volume
  - Updates the jobStatus in scicat

**Comment by sbliven** [comment]
I discussed this with @consolethinks and @minottic. It would be immediately useful for testing the scicat-backend-next implementation of jobs (eg https://github.com/SciCatProject/scicat-backend-next/issues/841 and related)

**Comment by consolethinks** [comment]
I have a patchset that would add a RabbitMQ instance and would set up scicatlive to use it whenever we create new jobs using the /Jobs endpoint. I wouldn't mind creating a pull request for it, but I'd prefer this to be in its own branch based on master (with v3 of backend)
