### ISSUE TITLE
How to open the SciCAT on server terminal

### ISSUE THREAD

**Issue by hfahad** [SciCatProject/scicatlive#24]
Dear SciCAT members,

I have already installed SciCAT on my server, which my university provided me. For your information, it is accessible only through terminal access, so I can access it via SSH command. Could you please tell me how I can open the "http://localhost/" link? I do not have any graphical interface for this server; only the terminal is available.

Kind regards,
Hafiz

**Comment by minottic** [comment]
hi @hfahad you would need to open a tunnel from your laptop to your remote server to port 80 I guess. Try doing:
```
ssh ${USER}@${IP} -D 80 -q -N -i
```

$USER is the one you use to ssh to that machine and $IP is the one of the server. If that doesn't work try double-checking the ssh options. 

After this go to localhost on your browser (make sure the docker-compose/scicatlive is running on the remote server)

**Comment by minottic** [comment]
closed as solution was provided
