### ISSUE TITLE
Incorrect admin password for v4 BE

### ISSUE THREAD

**Issue by consolethinks** [SciCatProject/scicatlive#303]
The admin password is incorrect for v4 backend in the README.md at https://github.com/SciCatProject/scicatlive/blob/main/services/backend/services/v4/README.md

**Comment by minottic** [comment]
I've changed [this](https://github.com/SciCatProject/scicatlive/blob/main/services/backend/services/v4/config/functionalAccounts.json#L4) recently to comply with the readme and be the same as v3. Unfortunately, if you had the DB already you might need to recreate it otherwise the PWD is not updated

**Comment by consolethinks** [comment]
Ahh, makes sense. After deleting the old DB volume, the issue is fixed! I'll close this then
