### ISSUE TITLE
Refactor to modular components

### ISSUE THREAD

**Issue by minottic** [SciCatProject/scicatlive#35]

**Comment by sbliven** [comment]
Carlo writes:
> What I had in mind is more or less what you suggested, so: every “config” should become a “service” with a dedicated docker-compose. There should then be a high-level docker-compose which just [includes](https://docs.docker.com/compose/multiple-compose-files/include/) them then. Then every user is free to decide what service to use, just by using the highlevel docker-compose with docker-compose up <service1> <service2>... . I am still unclear of some details, for example if it is possible to have dependencencies between different docker-composes and I think we will need to use profiles for bundling services together in the high-level docker-compose.
This would make the services a little more independent (at least easing the addition of a new one), but I still think we’ll need to manage quite some configurations. In the end we are just moving the “profiles of a mono docker-compose” to multiple docker-composes

**Comment by sbliven** [comment]
Dependencies between compose files are possible using [extends](https://docs.docker.com/compose/multiple-compose-files/extends/).

Defining a docker-compose with some selection of services should be straightforward. However, I'm less certain about how to manage the config files without duplicating a lot of json.

**Comment by minottic** [comment]
but I'd like to avoid extending everywhere there's a dependency. But let's discuss in today's meeting

**Comment by minottic** [comment]
I had another thought and I think we should proceed with `includes` and `profiles`. `profiles` cannot be avoided I am afraid as having the `old backend` and the `new backend` means that, if we want to keep the user's interaction to a minimum, we need a way to bundle `new be and fe` and `old be and fe`. 

For this, I would suggest, as a start, that every component has: 
1. a profile with its name (unique - this is needed because docker-compose does not support profiles and services together as CLI arguments) and others which work for grouping
2. a README file that describes the options
3. example configuration files that include all available options
4. configuration files with the applied configuration
5. explicit traefik labelling

Once we have a minimal refactor which follows this, and we have added the most urgent components, we can expand on this concept and add more configuration (I would keep a single one for the moment, but we can rediscuss once we reach that point). For example, we could add other profiles and decide how to create the [dev environment](https://github.com/SciCatProject/scicatlive/issues/38).

I will open an example PR soon

**Comment by minottic** [comment]
see PR: #52

**Comment by minottic** [comment]
closed by linked PRs/issues
