### ISSUE TITLE
DEV doesn't initialize the database

### ISSUE THREAD

**Issue by sbliven** [SciCatProject/scicatlive#380]
DEV mode uses a different database from production: `dev_be_next` rather than `dacat` (see [
services/backend/services/v4/config/.dev.env](https://github.com/SciCatProject/scicatlive/blob/main/services/backend/services/v4/config/.dev.env).

However, the [init.sh](https://github.com/SciCatProject/scicatlive/blob/main/services/mongodb/config/init.sh) script always initializes the production database. Thus the DEV database will be empty upon creation.

**Comment by minottic** [comment]
do you think it's better to reuse the prod DB in DEV as well, or rather seed the DEV db?

**Comment by sbliven** [comment]
I would keep it separate in case the mocha tests overwrite the db

**Comment by sbliven** [comment]
Instead, how about the init.sh script takes $DB from the environment. Then it gets set DB="dacat" in the v3 compose, DB="dacat-next" in v4, and "dev_be_next" in v4+dev

**Comment by sbliven** [comment]
Or we could be more consistent about the naming, eg `dacat-${BE_VERSION}${DEV:+-dev}`

**Comment by minottic** [comment]
yes, the DEV env var is what I would use as well. I think I was always afraid to rename it, not to mess up with people already using the DB. So maybe for now we could simply prepend/append the DEV part

**Comment by sbliven** [comment]
Renaming dev is no problem. `dacat` is the only one I would think twice about renaming (and even there, maybe it's better to do it now before we have actual scicatlive production instances).

Another thing, should each db be in its own volume? Or would it be ok to just have one mongo volume with all databases

**Comment by minottic** [comment]
for me it would be fine keeping everything in the same DB. 

What jd

**Comment by minottic** [comment]
closed by #381
