### ISSUE TITLE
Https via Letsencrypt

### ISSUE THREAD

**Issue by belfhi** [SciCatProject/scicatlive#58]
Traefik allows for automatic issuance of TLS certificates from letsencrypt via a few configuration options.
Https should not be optional even in a test setup.

**Comment by minottic** [comment]
yes, this won't work with localhost as letsenrcypt will be unable to do the callback from its ca to the service. We can brainstorm on this offline, but what I had in mind was mostly a "documentation" improvement, basically what it's partially covered [here](https://github.com/SciCatProject/scicatlive/pull/59#issuecomment-2015060297).

**Comment by consolethinks** [comment]
Ohh, okay, I have only seen the description of this issue so I wasn't sure if it was really a good idea, but that might make more sense

**Comment by minottic** [comment]
closed by #140
